Update Route18.asm
Nog-Frog/pokered pull request #112
Opened 2020-06-30 15:59 UTC by Shako-24

2020-07-01 06:55 UTC, Nog-Frog requested changes

2020-07-01 06:55 UTC, Nog-Frog commented on text/maps/Route18.asm
> +	cont "#ימונים חדשים."
```suggestion
	text "אני מחפש #ימונים"
	line "חדשים בכל כר"
	cont "דשא."
```

2020-07-01 06:55 UTC, Nog-Frog commented on text/maps/Route18.asm
> +	text "טששש!"
באנגלית "Tch" זה הצליל שבעברית נקרא "לצקצק בלשון".
```suggestion
	text "צק!"
```

2020-07-01 06:55 UTC, Nog-Frog commented on text/maps/Route18.asm
> +	cont "קולות הציפור שלי?"
```suggestion
	line "אתה אוהב את קריאת"
	cont "הציפור שלי?"
```

2020-07-01 06:55 UTC, Nog-Frog commented on text/maps/Route18.asm
> +	text "דרך 18"
```suggestion
	text "דרך 81"
```
שכחתי להוסיף את זה למדריך, אבל צריך להפוך מספרים כדי שיודפסו נכון בעברית.

2020-07-03 05:03 UTC, maybal9 commented
לא ראיתי שהגשת PR ותרגמתי בעצמי :(
סוגרת

2020-07-03 05:03 UTC, closed without merging