Update FightingDojo.asm
Nog-Frog/pokered pull request #32
Opened 2020-06-09 21:42 UTC by Shako-24

2020-06-10 09:59 UTC, Nog-Frog requested changes

2020-06-10 09:59 UTC, Nog-Frog commented on text/maps/FightingDojo.asm
> +	cont "את הסמל שלנו"
כשהוא אומר emblem לא ברור למה הוא מתכוון, אבל לדעתי הרבה יותר סביר שהכוונה היא לסוג כלשהו של קמע, או איזה פסל. אולי הוא מתכוון לבאנרים שנמצאים על הקיר מאחוריו. צריך לחשוב על זה, ככה או ככה זה לא סמל; אם אתה לא מוצא תשובה שנראית לך טובה, אפשר להשאיר באנגלית ולהוסיף TODO ואני אחזור לזה בסוף.

2020-06-10 09:59 UTC, Nog-Frog commented on text/maps/FightingDojo.asm
> +	line "לאתגר?"
שים לב שצריך לצמצם פה את השורות... יש לך שורה שלמה בשביל מילה אחת

2020-06-10 09:59 UTC, Nog-Frog commented on text/maps/FightingDojo.asm
> +	cont "!ימון מלחמה#"
פוקימון מסוג לחימה / פוקימון לחימה

2020-06-10 09:59 UTC, Nog-Frog commented on text/maps/FightingDojo.asm
> +	line "!מה שתרצה"
זה לא תרגום נכון. הכוונה היא שהשחקן יכול לבחור אחד מהפוקימונים. תרגום יותר מדוייק יהיה משהו כמו "בחר אחד מהם! מה שאתה מעדיף!".
לא חייבים אפילו להישאר נאמנים למקור מילה במילה. לפעמים מספיק טוב לתרגם את זה בסגנון "בחר אחד!".

2020-06-10 09:59 UTC, Nog-Frog commented on text/maps/FightingDojo.asm
> +	cont "אל תצפה שנרחם עליך!"
מעל 18 תווים

2020-06-10 09:59 UTC, Nog-Frog commented on text/maps/FightingDojo.asm
> +	line "להתאמן בקארטה איתנו!"
מעל 18 תווים

2020-06-10 10:29 UTC, Shako-24 commented on text/maps/FightingDojo.asm
> +	cont "את הסמל שלנו"
יכול להיות שהתרגום לעברית יהיה  'תג'? כי במכוני פוקימונים זוכים בתגים בסוף? בכל מקרה אני אשאיר את זה בעברית כי אני באמת לא בטוחה לגבי זה :)

2020-06-11 15:40 UTC, Nog-Frog commented
מעולה, תודה רבה! :)

2020-06-11 15:40 UTC, merged