PokeDex - Hebrew translation
Nog-Frog/pokered pull request #51
Opened 2020-06-14 09:03 UTC by maybal9

this is the Hebrew version of PokeDex. 
I used Hebrew terms wherever I could - pokemon names and moves names

2020-06-14 10:59 UTC, Nog-Frog requested changes
סימנתי שינויים קטנים קטנים.
אין עליך, נראה מעולה ממש!

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next  "רעל כדי לרתק"
לשתק במקום לרתק

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next  "והופך לקונכייה."
לשריון, כי הוא צב :)

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	text  "#ימון פרה"
אולי להוסיף מקף אחרי "פרה"? כי זה נראה כמו פוקימון פרה היסטורי (Historic cow pokemon)

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
>  _KangaskhanDexEntry::
מסתבר שהן יכולות להיות רק בנות, ושאין זכרים כאלה!
אז את כינויי הגוף אפשר לשנות לנקבה.

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
>  _ClefairyDexEntry::
יש להן יחס מגדרי של פי 3 נקבות מאשר זכרים, לכן אפשר לשנות את כינויי הגוף.

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +_ClefableDexEntry::
יש להן יחס מגדרי של פי 3 נקבות מאשר זכרים, לכן אפשר לשנות את כינויי הגוף.

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +_VulpixDexEntry::
יש להן יחס מגדרי של פי 3 נקבות מאשר זכרים, לכן אפשר לשנות את כינויי הגוף.

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +_NinetalesDexEntry::
יש להן יחס מגדרי של פי 3 נקבות מאשר זכרים, לכן אפשר לשנות את כינויי הגוף.

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +_JigglypuffDexEntry::
יש להן יחס מגדרי של פי 3 נקבות מאשר זכרים, לכן אפשר לשנות את כינויי הגוף.

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +_WigglytuffDexEntry::
יש להן יחס מגדרי של פי 3 נקבות מאשר זכרים, לכן אפשר לשנות את כינויי הגוף.

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +_StarmieDexEntry::
להוסיף שורה רווח בין לבין

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "כלי הנשק המרכזי"
העיקרי במקום במרכזי

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "טובי השחיינים"
אולי "טובי השחיינים האנושיים"? או "טובי בני האדם השחיינים"?

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "בעת זעם, הוא"
אולי "כשכועס" במקום "בעת זעם"?

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "שמת כשקונכייתו"
אולי "שנכחד" במקום "שמת"?

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	text "צבתותיו הן לא"
הם*

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "מופיע לאנשים"
מופיע בפני אנשים / מתגלה לאנשים

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "קרח"
אולי "בהרים מושלגים" או "פסגות מושלגות" או משהו בסגנון?

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	text "חי בצללים של"
בצילם*

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	text "הזלזל של הבצל"
איזה קטע. תמיד חשבתי שזה סלרי.

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "הלכאורה מביא"
תיקון: "לכאורה מביאה"

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "הטריטוריה שלו."
במקום טריטוריה, "תחום" (לפי מילון המונחים של האקדמיה) :)

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	page "הוא ינדנד אותו"
ינער / ינפנף אולי?

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	text "#ימון ברוטלי"
אכזרי במקום ברוטלי

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	text "עם זריזות"
אולי "בעל זריזות"?

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "מהלכים עוצמתיים"
אפשר לשנות ל"מתקפות עוצמתיות" אולי. זה נכון שבכללי התרגום הוא "מהלכים" אבל אפשרי לתרגם ל"מתקפות" אם הקונטקסט מתאים. לא חובה.

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "#ימון הזה"
תיקון: חסרה ה' הידיעה

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "זיקית. הוא"
תיקון: כמו של זיקית

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "אחד מראשיו יצנח"
ינשור במקום יצנח?

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "שבמקרים נדירים,"
אולי "מספרים שבמקרים"? באנגלית Legend has it לא מתיחס לשום אגדה ספציפית, ובעברית זה פחות ככה.

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "לריסוק, לכבילת"
ניסוח מחדש:
"בזמן קרב, משתמש"
"בזנבו העוצמתי כדי"

"לרסק, לכבול,"
"ולשבור את עצמותיו"
"של הטרף"

2020-06-14 10:59 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "להישאר באוויר"
אולי "להישאר בתעופה"?

2020-06-14 14:00 UTC, maybal9 commented on text/pokedex.asm
>  _ClefairyDexEntry::
אני באמת התלבטתי מה לעשות במקרים האלה

2020-06-14 14:10 UTC, maybal9 commented on text/pokedex.asm
> +	next "מהלכים עוצמתיים"
מסכימה

2020-06-14 14:48 UTC, maybal9 commented on text/pokedex.asm
> +	text "עם זריזות"
לדעתי פחות מתאים בעל זריזות, כי המשך המשפט אומר שעם הזריזות הזאת הוא נותן אשליה שיש יותר מאחד.
מה דעתך על הניסוח האלטרנטיבי הזה:
"בעל זריזות"
"ומהירות של"
"נינג'ה, אשר בעזרתן"

"הוא מסוגל"
"לייצר אשליה"
"שיש יותר מאחד"

2020-06-14 14:48 UTC, maybal9 commented on text/pokedex.asm
> +	text "צבתותיו הן לא"
צבת זה נקבה, לפחות צבת במשמעות של כלי עבודה.
[https://he.wiktionary.org/wiki/%D7%A6%D7%91%D7%AA#%D7%A6%D6%B0%D7%91%D6%B8%D7%AA](url)

2020-06-16 13:30 UTC, Nog-Frog requested changes
שינויים אחרונים וסיימנו 🦾

2020-06-16 13:30 UTC, Nog-Frog commented on text/pokedex.asm
> +	next "מתוק וכובש, לו"
תיקון: לה

2020-06-16 13:30 UTC, Nog-Frog commented on text/pokedex.asm
> +	text "עם זריזות"
נשמע מצוין, אני בעד

2020-06-16 13:30 UTC, Nog-Frog commented on text/pokedex.asm
> +	text "צבתותיו הן לא"
אה. אם כך, יש לשנות את כינויי הגוף של המשך ההסבר לנקבה. כאן כתוב "הן" אבל שתי שורות למטה כתוב "הם משמשים".

2020-06-17 09:00 UTC, maybal9 commented on text/pokedex.asm
> +	next "מתוק וכובש, לו"
בעיקרון המעריצים הם לקסם האישי אבל זה באמת לא נשמע טוב... אני אנסח את זה טיפה שונה

2020-06-17 09:14 UTC, maybal9 commented
תוקן!

2020-06-17 16:04 UTC, merged