Update FuchsiaCity.asm
Nog-Frog/pokered pull request #60
Opened 2020-06-15 21:00 UTC by Shako-24

2020-06-16 14:08 UTC, Nog-Frog requested changes
פלוס בעיות פיסוק

2020-06-16 14:08 UTC, Nog-Frog commented on text/maps/FuchsiaCity.asm
> +	text "ביקרת ב"
ב בשורה נפרדת

2020-06-16 14:08 UTC, Nog-Frog commented on text/maps/FuchsiaCity.asm
> +	cont ".איזור הספארי"
חסרה ל'

2020-06-16 14:08 UTC, Nog-Frog commented on text/maps/FuchsiaCity.asm
> +	line ".כמו #כדור"
פוכדור כותבים "פוכדור" (בלי סולמית).

2020-06-16 14:08 UTC, Nog-Frog commented on text/maps/FuchsiaCity.asm
> +        para "ימון אמהי#"
יש כאן טאב מיותר

2020-06-16 14:08 UTC, Nog-Frog commented on text/maps/FuchsiaCity.asm
> +	cont ".כיס בבטן שלו"
למעשה, הן יכולות להיות רק נקבות.
(כן, אני יודעת שאין לפוקימונים מין בדור 1, אבל בדורות הבאים הן רק נקבות).
אז אפשר לשנות את כינויי הגוף לנקבה.

2020-06-16 14:08 UTC, Nog-Frog commented on text/maps/FuchsiaCity.asm
> +	line ".למאובן"
נקודה מיותרת

2020-06-17 16:36 UTC, Nog-Frog requested changes

2020-06-17 16:36 UTC, Nog-Frog commented on text/maps/FuchsiaCity.asm
> +	line "מועדון #ימון"
```suggestion
	line "מכון #ימון"
```

2020-06-17 16:36 UTC, Nog-Frog commented on text/maps/FuchsiaCity.asm
> +	cont "מאמן: צפע"
```suggestion
	cont "מנהיג: צפע"
```

2020-06-17 16:36 UTC, Nog-Frog commented on text/maps/FuchsiaCity.asm
>  	line "כזה זה עניין"
```suggestion
	para "לתפוס אחת"
	line "כזו זה עניין"
```

2020-06-18 14:02 UTC, maybal9 requested changes

2020-06-18 14:02 UTC, maybal9 commented on text/maps/FuchsiaCity.asm
> +	line "באיזור הספארי?"
```suggestion
	text "ניסית את"
	line "משחק הספארי?"
```

2020-06-18 14:02 UTC, maybal9 commented on text/maps/FuchsiaCity.asm
> +	cont "לתפוס #ימונים."
```suggestion
	cont "יש #ימונים שתוכל"
	cont "לתפוס רק שם."
```

2020-06-18 14:02 UTC, maybal9 commented on text/maps/FuchsiaCity.asm
> +	cont "לאיזור הספארי."
```suggestion
	cont "באיזור הספארי."
```
גן החיות נמצא בתוך מתחם הספארי

2020-06-18 14:02 UTC, maybal9 commented on text/maps/FuchsiaCity.asm
> +	para "בחוץ מאחורה"
```suggestion
	para "מאחורה"
```

2020-06-18 14:02 UTC, maybal9 commented on text/maps/FuchsiaCity.asm
> +	line "נמצא משחק ספארי"
```suggestion
	line "נמצא משחק הספארי"
```

2020-06-18 14:02 UTC, maybal9 commented on text/maps/FuchsiaCity.asm
> +	line "WARDEN's HOME";TODO
במקום אחר תרגמו את המילה warden 
לפקח.

2020-06-18 14:02 UTC, maybal9 commented on text/maps/FuchsiaCity.asm
> +	line "כזה זה עניין"
בת מזל היא נקבה

2020-06-18 14:02 UTC, maybal9 commented on text/maps/FuchsiaCity.asm
> +	cont "והוחזר לחיים."
עדיף להיצמד לניסוח המקביל בפוקדע:
```suggestion
	para "ימון ששוחזר#"
	line "ממאובן"
```

2020-06-18 14:02 UTC, maybal9 commented on text/maps/FuchsiaCity.asm
> +	cont "והוחזר לחיים."
עדיף להיצמד לניסוח המקביל בפוקדע

2020-06-19 17:07 UTC, maybal9 approved these changes

2020-06-19 17:07 UTC, Nog-Frog commented on text/maps/FuchsiaCity.asm
> +	line "WARDEN's HOME";TODO
נכון, אבל אין בעיה כרגע להשאיר את זה ב-todo.
זה בדיוק מקביל למה שביקשתי בהנחיות לתרגום. לי נראה תקין, מסמנת את ההערה כ-resolved

2020-06-19 17:07 UTC, merged