Update SaffronGates.asm
Nog-Frog/pokered pull request #65
Opened 2020-06-17 10:47 UTC by Shako-24

2020-06-17 17:06 UTC, maybal9 requested changes
נראה שהטקטס המקורי נכתב בסלנג ולכן כדאי לשמר את המשלב הלשוני.
אני חושבת שאפשר לתרגם את המילה "Gee"
ל"וואי", אבל אם יש לך תרגום יותר טוב שעדיין ישמע סלנג ישראלי אז עדיף.

2020-06-17 17:06 UTC, maybal9 commented on text/maps/SaffronGates.asm
> +	line "אלוהים, אני צמא!"
```suggestion
	line "וואי, אני צמא!"
```
```suggestion
	line "יואו, אני צמא!"
```

2020-06-17 17:06 UTC, maybal9 commented on text/maps/SaffronGates.asm
> +	line "הכניסה חסומה."
```suggestion
	line "הכניסה סגורה."
```

2020-06-17 17:06 UTC, maybal9 commented on text/maps/SaffronGates.asm
> +	line "גרוני ניחר!"
```suggestion
	text "וואי אחי!"
	line "אני מיובש!"
```

2020-06-17 17:06 UTC, maybal9 commented on text/maps/SaffronGates.asm
> +	cont "אלוהים, תודה!@@"
```suggestion
	cont "וואי, תודה!@@"
```

2020-06-17 17:06 UTC, maybal9 commented on text/maps/SaffronGates.asm
> +	cont "אם ברצונך להגיע"
```suggestion
	cont "אם אתה רוצה להגיע"
```

2020-06-17 17:06 UTC, maybal9 commented on text/maps/SaffronGates.asm
> +	cont "אתה מוזמן לעבור"
```suggestion
	cont "אתה יכול לעבור."
```

2020-06-17 17:10 UTC, Shako-24 commented
> נראה שהטקטס המקורי נכתב בסלנג ולכן כדאי לשמר את המשלב הלשוני.
> אני חושבת שאפשר לתרגם את המילה "Gee"
> ל"וואי", אבל אם יש לך תרגום יותר טוב שעדיין ישמע סלנג ישראלי אז עדיף.

צודקת, תודה :)

2020-06-19 06:43 UTC, maybal9 approved these changes

2020-06-19 06:44 UTC, merged