Update SSAnne1F.asm
Nog-Frog/pokered pull request #66
Opened 2020-06-17 10:58 UTC by Shako-24

2020-06-17 16:50 UTC, maybal9 requested changes
שינויים קטנטנים.
האם לדעתך תרגום ישיר מצרפתית כאן לא יבלבל את הקורא שלא יודע צרפתית?
למשל ב"לה מלצר"

2020-06-17 16:50 UTC, maybal9 commented on text/maps/SSAnne1F.asm
> +	para "אשמח להכין לך"
```suggestion
	para "אשמח להגיש לך"
```

2020-06-17 16:50 UTC, maybal9 commented on text/maps/SSAnne1F.asm
> +	line "מהאורחים"
trailing white space at the end of line

2020-06-17 16:50 UTC, maybal9 commented on text/maps/SSAnne1F.asm
> +	cont "המשועממים."
```suggestion
	cont "המשועממים!"
```

2020-06-17 17:07 UTC, Shako-24 commented on text/maps/SSAnne1F.asm
> +	para "אשמח להכין לך"
...האמת שרציתי לשמור על הדיאלקט הצרפתי אבל אולי זה באמת לא עובד בכתב 

> שינויים קטנטנים.
> האם לדעתך תרגום ישיר מצרפתית כאן לא יבלבל את הקורא שלא יודע צרפתית?
> למשל ב"לה מלצר"

2020-06-18 08:15 UTC, Nog-Frog commented on text/maps/SSAnne1F.asm
> +	para "אשמח להכין לך"
אני חושבת שחשוב לשמור על המבטא הצרפתי, זה גורם לדמות להישמע מצחיקה וזה כל הקטע שלה.
אני מסכימה ש"לה מלצר" אולי באמת לא הכי עובד בכתב; אבל אני חושבת שצריך למצוא לו חלופה. אם יש רעיון לגבי איך מעבירים מבטא צרפתי בצורה יותר ברורה, מוזמנים ליישם; אם לא, לדעתי אפשר או להשאיר "לה מלצר" (זה לא מושלם אבל גם לא נורא), או להשאיר באנגלית le waiter ולהוסיף TODO ופשוט... נתמודד עם זה אחר-כך או משהו

2020-06-18 10:15 UTC, Shako-24 commented on text/maps/SSAnne1F.asm
> +	para "אשמח להכין לך"
'מה עם 'לה גרסון?

2020-06-18 11:03 UTC, Nog-Frog commented on text/maps/SSAnne1F.asm
> +	para "אשמח להכין לך"
לה גרסון נשמע מעולה! זה באמת שם למלצר בצרפתית.
מרגיש לי שאם מישהו בחיים שלו לא שמע צרפתית, הוא יהיה מבולבל ככה או ככה, זה כבר לא אשמתנו... הרי זה היה ככה באנגלית.
אולי משהו כמו "אני לה גרסון - כלומר, ממלצר - של הספינה הזאת!" בדיאלוג הראשון, ואז בשאר אפשר פשוט לכתוב "לה גרסון" בלי ההסבר של מלצר.

2020-06-18 12:16 UTC, Shako-24 commented on text/maps/SSAnne1F.asm
> +	para "אשמח להכין לך"
מעולה :)

2020-06-19 17:11 UTC, merged