Update MtMoon1F.asm
Nog-Frog/pokered pull request #67
Opened 2020-06-18 12:15 UTC by Shako-24

2020-06-18 15:05 UTC, maybal9 requested changes
בגדול כדאי להוריד קצת את המשלב הלשוני כדי שהטקסט יישמע ישראלי-יומיומי ופחות ספרותי, בהתאם למקור.

2020-06-18 15:05 UTC, maybal9 commented on text/maps/MtMoon1F.asm
> +	line "אותי! אתה בסך!"
```suggestion
	line "אותי! אה, אתה בסך!"
```

2020-06-18 15:05 UTC, maybal9 commented on text/maps/MtMoon1F.asm
> +	line "הבנות."
```suggestion
	line "להשוויץ לבנות."
```

2020-06-18 15:05 UTC, maybal9 commented on text/maps/MtMoon1F.asm
> +	cont "משתיארתי!"
```suggestion
	cont "ממה שחשבתי!"
```
כדאי להוריד קצת את המשלב הלשוני

2020-06-18 15:05 UTC, maybal9 commented on text/maps/MtMoon1F.asm
> +	cont "מכנופיית רוקט!"
```suggestion
	cont "מצוות רוקט!"
```
@Nog-Frog מה אומרת?

2020-06-18 15:05 UTC, maybal9 commented on text/maps/MtMoon1F.asm
> +	text "תעבור דרך המערה"
בלשון ציווי במקום בעתיד

2020-06-18 15:05 UTC, maybal9 commented on text/maps/MtMoon1F.asm
> +	cont "הוא יפיק לך תועלת."
אולי קשוח במקום עקשן?
```suggestion
	line "קשוח! אבל הוא"
	cont "יכול להיות שימושי"
	cont "אם תתפוס אחד."
```

2020-06-18 15:05 UTC, maybal9 commented on text/maps/MtMoon1F.asm
> +	cont "ואתה?"
```suggestion
	cont "ומה אתה?"
```

2020-06-18 15:05 UTC, maybal9 commented on text/maps/MtMoon1F.asm
> +	line "איבדתי את זה!"
@Nog-Frog התרגום תלוי הקשר, יכול להיות גם:
הפסדתי את זה.
מה דעתך?

2020-06-18 15:26 UTC, Shako-24 commented on text/maps/MtMoon1F.asm
> +	cont "הוא יפיק לך תועלת."
זהו.. לא הייתי בטוחה.. מה הכוונה כאן..

2020-06-18 15:29 UTC, Shako-24 commented on text/maps/MtMoon1F.asm
> +	cont "משתיארתי!"
צודקת, זה מה שכתבתי בהתחלה 👍

2020-06-18 15:44 UTC, Shako-24 commented
> בגדול כדאי להוריד קצת את המשלב הלשוני כדי שהטקסט יישמע ישראלי-יומיומי ופחות ספרותי, בהתאם למקור.
👍

2020-06-18 15:45 UTC, Shako-24 commented on text/maps/MtMoon1F.asm
> +	cont "מכנופיית רוקט!"
בתרגומים קודמים נוגה אמרה לי שזה צריך להיות כנופיית רוקט

2020-06-19 06:34 UTC, maybal9 commented on text/maps/MtMoon1F.asm
> +	cont "מכנופיית רוקט!"
אז מה שנוגה אומרת :)

2020-06-19 06:37 UTC, maybal9 approved these changes

2020-06-19 06:37 UTC, merged