Update MtMoonPokecenter.asm
Nog-Frog/pokered pull request #74
Opened 2020-06-20 10:14 UTC by Shako-24

2020-06-21 14:13 UTC, maybal9 requested changes
הצעות קטנות לשיפור

2020-06-21 14:13 UTC, maybal9 commented on text/maps/MtMoonPokecenter.asm
> +	line "שם עד 6 #ימונים."
עדיף: "אפשר להחזיק שם עד 6 #ימונים"

2020-06-21 14:13 UTC, maybal9 commented on text/maps/MtMoonPokecenter.asm
> +	text "איש: שתדע שאני"
הצעה: "שתדע שאצלי אין החזרים!"

2020-06-21 21:30 UTC, Shako-24 commented on text/maps/MtMoonPokecenter.asm
> +	text "איש: שתדע שאני"
👍

2020-06-21 21:30 UTC, Shako-24 commented on text/maps/MtMoonPokecenter.asm
> +	line "שם עד 6 #ימונים."
👍

2020-06-22 08:13 UTC, maybal9 approved these changes

2020-06-22 08:13 UTC, merged