Update SSAnne2FRooms.asm
Nog-Frog/pokered pull request #83
Opened 2020-06-21 09:38 UTC by Shako-24

2020-06-21 14:18 UTC, maybal9 requested changes
הצעות קטנטנות לשיפור

2020-06-21 14:18 UTC, maybal9 commented on text/maps/SSAnne2FRooms.asm
> +	text "להתחרות בילדים"
אולי: "התחרות נגד ילדים גורמת לי להרגיש צעיר"?

2020-06-21 14:18 UTC, maybal9 commented on text/maps/SSAnne2FRooms.asm
> +	line "all out!";TODO
הצעות: "אני בחוץ!"
או: "אני גמרתי!"

2020-06-21 14:18 UTC, maybal9 commented on text/maps/SSAnne2FRooms.asm
> +	text "הו, אני מחבב"
```suggestion
	text "הו, אני מעריץ"
```

2020-06-21 21:20 UTC, Shako-24 commented on text/maps/SSAnne2FRooms.asm
> +	text "להתחרות בילדים"
נשמע יותר טוב, תודה!

2020-06-21 21:20 UTC, Shako-24 commented on text/maps/SSAnne2FRooms.asm
> +	line "all out!";TODO
👍

2020-06-22 08:12 UTC, maybal9 approved these changes

2020-06-22 08:12 UTC, merged