Translated Giovanni's dialogue
Nog-Frog/pokered pull request #84
Opened 2020-06-21 12:57 UTC by Kokilida2

2020-06-22 08:42 UTC, maybal9 requested changes
אהבתי את התרגום שלך! הוספתי כמה הערות קטנות

2020-06-22 08:42 UTC, maybal9 commented on text/maps/ViridianGym.asm
> +	cont "עוד הפעם!"
```suggestion
	cont "עוד פעם!"
```

2020-06-22 08:42 UTC, maybal9 commented on text/maps/ViridianGym.asm
> +	text "חה!"
```suggestion
	text "הא!"
```
חה משדר צחוק מסוים אבל כאן מנסים לשדר הפתעה ולכן נראה לי ש"הא!" יותר מתאים בהקשר הזה

2020-06-22 08:42 UTC, maybal9 commented on text/maps/ViridianGym.asm
> +	cont "TEAM ROCKET"
```suggestion
	cont "TEAM ROCKET" ;TODO
```

2020-06-22 08:42 UTC, maybal9 commented on text/maps/ViridianGym.asm
> +	cont "הנחותים לי!"
נחותים זאת מילה קצת חזקה, עדיף למצוא תרגום טוב יותר, אולי כפופים? חברי הצוות שלי? אולי פשוט האחרים?

2020-06-22 08:42 UTC, maybal9 commented on text/maps/ViridianGym.asm
> +	line "ללמידת #ימונים!"
```suggestion
	line "ללימודי #ימונים!"
```
זה אפילו נשמע קצת מדעי

2020-06-22 08:42 UTC, maybal9 commented on text/maps/ViridianGym.asm
> +	line "מן הימים!"
אולי:
```suggestion
	para "יום יבוא ועוד"
	line "ניפגש שוב!"
```

2020-06-22 08:42 UTC, maybal9 commented on text/maps/ViridianGym.asm
> +	line "כישוריך המעולים"
```suggestion
	para "הוא הוכחה"
	line "לכישוריך המעולים"
```

2020-06-22 08:42 UTC, maybal9 commented on text/maps/ViridianGym.asm
> +	para "איתו בידך, אתה"
```suggestion
	para "עם זה, אתה"
```

2020-06-22 08:42 UTC, maybal9 commented on text/maps/ViridianGym.asm
> +	line "כשניהלתי את הGYM," ; TODO
```suggestion
	line "כשניהלתי את המכון,"
```

2020-07-03 15:48 UTC, Nog-Frog commented
No longer needed.

2020-07-03 15:48 UTC, closed without merging