Update UndergroundPathRoute7Copy.asm
Nog-Frog/pokered pull request #85
Opened 2020-06-21 22:03 UTC by Shako-24

2020-06-22 08:26 UTC, maybal9 requested changes

2020-06-22 08:26 UTC, maybal9 commented on text/maps/UndergroundPathRoute7Copy.asm
> +	text "אתה פה לקנות"
```suggestion
	text "אתה פה כדי לקנות"
```

2020-06-22 08:26 UTC, maybal9 commented on text/maps/UndergroundPathRoute7Copy.asm
> +	cont "מערבה!"
```suggestion
	para "פשוט צא החוצה"
	line "והתקדם מערבה!"
```
לשון ציווי במקום לשון עתיד

2020-06-23 10:07 UTC, Nog-Frog requested changes

2020-06-23 10:07 UTC, Nog-Frog commented on text/maps/UndergroundPathRoute7Copy.asm
> +	cont "האביב אבל..."
תורגם "כל-בו אביב".
```suggestion
	line "בכל-בו אביב אבל..."
```

2020-06-23 10:07 UTC, Nog-Frog commented on text/maps/UndergroundPathRoute7Copy.asm
> +	cont "ממול."
אפשר לאחד
```suggestion
	cont "לך לבניין ממול."
```

2020-06-23 10:35 UTC, merged