Update HallOfFame.asm
Nog-Frog/pokered pull request #86
Opened 2020-06-21 22:23 UTC by Shako-24

2020-06-22 08:17 UTC, maybal9 requested changes
שינויים קטנים והצעה לתרגום

2020-06-22 08:17 UTC, maybal9 commented on text/maps/HallOfFame.asm
> +	line "אלופי המאמנים"
```suggestion
	para "אלופי ליגת"
	line " ה#ימון"
```

2020-06-22 08:17 UTC, maybal9 commented on text/maps/HallOfFame.asm
> +	cont "HALL OF FAMERs!";TODO
```suggestion
	cont "נכנסתם להיכל התהילה!"
```

2020-06-23 10:12 UTC, Nog-Frog requested changes

2020-06-23 10:12 UTC, Nog-Frog commented on text/maps/HallOfFame.asm
> +	text "OAK: א-המ!"
לזכור להוסיף TODO, אחרת לא אוכל למצוא את זה כשאני מחליפה את השמות.
```suggestion
	text "OAK: א-המ!" ; TODO
```

2020-06-23 10:12 UTC, Nog-Frog commented on text/maps/HallOfFame.asm
> +	line " ה#ימון"
רווח מיותר, אפשר לצמצם שורה
```suggestion
	line "ה#ימון זוכים"
```

2020-06-23 10:12 UTC, Nog-Frog commented on text/maps/HallOfFame.asm
> +	line "אתה <PLAYER>"
```suggestion
	line "<PLAYER>, אתה"
```
פסיק חסר

2020-06-23 10:12 UTC, Nog-Frog commented on text/maps/HallOfFame.asm
> +	cont "וה#ימון שלך"
הכוונה לכל הצוות.
```suggestion
	cont "וה#ימונים שלך"
```

2020-06-23 10:37 UTC, Nog-Frog requested changes

2020-06-23 10:37 UTC, Nog-Frog commented on text/maps/HallOfFame.asm
> +	cont "על ההישגים שלהם!"
אאא טעות שלי, בהערה הקודמת כשביקשתי לצמצם שורה, בטעות הוספתי כפילות של המילה "זוכים".
```suggestion
	line "ה#ימון זוכים"
	cont "לכבוד על ההישגים"
	cont "שלהם!"
```

2020-06-23 10:44 UTC, merged